# Generated by Django 5.2.3 on 2025-06-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=225, unique=True)),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=225)),
                ('body_preview', models.TextField(blank=True)),
                ('recieved_date', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
