# Generated by Django 5.2.3 on 2025-06-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mails',
            old_name='recieved_date',
            new_name='received_date',
        ),
    ]
