# Generated by Django 5.2.3 on 2025-06-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineer',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
