# Generated by Django 5.2.3 on 2025-06-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_updated_engineer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
